### ISSUE TITLE
Selenium::WebDriver::Error::WebDriverError: unable to obtain stable firefox connection in 60 seconds (127.0.0.1:7055)

### ISSUE THREAD

**Issue by anushamummina** [BRIDGE2THINK/video_grabber#1]
When I am trying to execute `VideoGrabber.new(url: "http://live.wsj.com/video/opinion-journal-donald-trump-jrs-russia-scandal/EDD478E3-C80B-447C-BC34-9EDCA85C66B7.html")` I am getting below error:

`Selenium::WebDriver::Error::WebDriverError: unable to obtain stable firefox connection in 60 seconds (127.0.0.1:7055)`

Could you please help on solving this.

**Comment by shideneyu** [comment]
Hello,

What is the OS you use? And Which version of Firerfox? This issue is a selenium issue that I also encountered using Ubuntu. If I remember correctly you should downgrade to Firefox 45

More info on https://github.com/seleniumhq/selenium/issues/835

Please tell me how it goes

**Comment by anushamummina** [comment]
My Firefox version is 53.0.2 and Selenium-webdriver version is:-2.53.4 and also why do we need selenium for this?

**Comment by shideneyu** [comment]
We are using a dependancy called `watir`. And it uses `selenium` to interact with real browser like Firefox or Chrome for example. `selenium` is the only way we have to use Firefox.

So the new Firefox versions are not compatible with Selenium it seems: 
http ://www.kenst.com/2016/10/selenium-webdriver-2-53-x-not-working-with-firefox-47-and-beyond/
So alternatively you can choose to pass the 'browser' parameter in VideoGraber change it to chrome or even better, Phantomjs.

In case you wish to use Phantomjs, you should install it in your local machine. Using Ubuntu you can run this: `sudo npm install phantomjs`
And then open the Phantomjs folder, go in lib and copy it into your path (/var/lib/ if I recall correctly)

Sorry for this to be so complicated, we have no control over our dependancies. Do not hesitate if you have more questions, as soon as you resolve this, the gem itself is truly worth it and resilient.

Sent from my Phone.

**Comment by anushamummina** [comment]
Thank you @shideneyu  When I have downgraded to firefox version to 46 Error has been resolved and I am getting data.
Below is my example I have used:
```

$ video_grabber = VideoGrabber.new(url: "http://live.wsj.com/video/opinion-journal-donald-trump-jrs-russia-scandal/EDD478E3-C80B-447C-BC34-9EDCA85C66B7.html").call
$ video_grabber.fetch_videos
   ["<video style=\"display: block;\" poster=\"https://m.wsj.net/video/20170713/071317opinionjunior/071317opinionjunior_640x360.jpg\" src=\"mediasource:http://www.wsj.com/6d3ee567-2dd3-4d50-8fca-35fe6b21a8c8\" id=\"videoplayer-player\" preload=\"none\" crossorigin=\"anonymous\" height=\"100%\" width=\"100%\" controls=\"true\"/>",
 "<video width=\"100%\" height=\"100%\" crossorigin=\"anonymous\" preload=\"none\" id=\"videoplayer-player\" src=\"mediasource:http://www.wsj.com/6d3ee567-2dd3-4d50-8fca-35fe6b21a8c8\" poster=\"https://m.wsj.net/video/20170713/071317opinionjunior/071317opinionjunior_640x360.jpg\" style=\"display: block;\" controls=\"true\"/>"]


```

but here I want video url which needs to be usedto play in android application. but I am getting video tags through which I can't play the video from other location

Could you please help me on how to embed this video urls in my application.

**Comment by shideneyu** [comment]
You're welcome @anushamummina. Well, at this point this is not the responsibility of VideoGrabber anymore. You are free to make a pull request if you want to add such a feature, but please bear notice that this was not intended in the first place.

But actually it's really easy to do so at this point, you only got to parse the url from this string. I assume here that this is : 'http://www.wsj.com/6d3ee567-2dd3-4d50-8fca-35fe6b21a8c8\' , so you only have to make a regexp to grab it (there's other ways than using a regexp, just take the string that begins by 'src=\"mediasource:' and ends by a space for instance.

I close this issue for the time being, do no hesitate if you have any further questions.
